### ISSUE TITLE
Expo Go Beta 

### ISSUE THREAD

**Issue by biller-aivy** [4TWIGGERS/react-native_3d_store#1]
![731A6C4C-0A69-4C99-965F-BB3CD93CCB8F](https://user-images.githubusercontent.com/88539760/181344712-33e7a066-37c7-404d-934c-417cd5f2c063.png)

**Comment by alexandrius** [comment]
You sure you have latest Expo Go Beta?

Even if yes the issue is unrelated to repo

**Comment by vasylnahuliak** [comment]
The same issue with release SDK 46
